In [2]:
from cpra.mp.data import read_data

In [2]:
lf = read_data(variable="sal", grid="hydro_compartment_v001", time_unit="annual", model_group_id=500, scenario_id=8, aggregate_type="mean")
lf.collect()

shape: (52, 1_665)
┌──────────┬────────────────────────┬───────────┬────────────────┬───┬────────┬──────┬──────┬──────┐
│ variable ┆ grid                   ┆ time_unit ┆ model_group_id ┆ … ┆ 1654   ┆ 1655 ┆ 1656 ┆ 1657 │
│ ---      ┆ ---                    ┆ ---       ┆ ---            ┆   ┆ ---    ┆ ---  ┆ ---  ┆ ---  │
│ str      ┆ str                    ┆ str       ┆ i32            ┆   ┆ f32    ┆ f32  ┆ f32  ┆ f32  │
╞══════════╪════════════════════════╪═══════════╪════════════════╪═══╪════════╪══════╪══════╪══════╡
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.2826 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.2291 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.2952 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.2497 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.3094 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ …        ┆ …                      ┆ …         ┆ …              ┆ … ┆ …      ┆ …    ┆ …    ┆ …    │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 2.2456 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.9269 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 3.0028 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 2.8109 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 4.1906 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
└──────────┴────────────────────────┴───────────┴────────────────┴───┴────────┴──────┴──────┴──────┘

In [4]:
lf = read_data(variable="sal", grid="hydro_compartment_v001", time_unit="annual", model_group_id=500, scenario_id=7, aggregate_type="mean")
lf.collect()

shape: (52, 1_665)
┌──────────┬────────────────────────┬───────────┬────────────────┬───┬────────┬──────┬──────┬──────┐
│ variable ┆ grid                   ┆ time_unit ┆ model_group_id ┆ … ┆ 1654   ┆ 1655 ┆ 1656 ┆ 1657 │
│ ---      ┆ ---                    ┆ ---       ┆ ---            ┆   ┆ ---    ┆ ---  ┆ ---  ┆ ---  │
│ str      ┆ str                    ┆ str       ┆ i32            ┆   ┆ f32    ┆ f32  ┆ f32  ┆ f32  │
╞══════════╪════════════════════════╪═══════════╪════════════════╪═══╪════════╪══════╪══════╪══════╡
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.2826 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.2291 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.1419 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.4668 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.402  ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ …        ┆ …                      ┆ …         ┆ …              ┆ … ┆ …      ┆ …    ┆ …    ┆ …    │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.6046 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.9306 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 0.6378 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 1.602  ┆ 0.0  ┆ 0.0  ┆ 0.0  │
│ sal      ┆ hydro_compartment_v001 ┆ annual    ┆ 500            ┆ … ┆ 1.2776 ┆ 0.0  ┆ 0.0  ┆ 0.0  │
└──────────┴────────────────────────┴───────────┴────────────────┴───┴────────┴──────┴──────┴──────┘

In [3]:
lf = read_data(variable="ffibs_coverage_ratio", grid="veg_grid_cell_v001", time_unit="annual", model_group_id=500, scenario_id=7)
lf.collect()
# lf.collect()["path"][1]

shape: (312, 8)
┌────────────┬────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ variable   ┆ grid       ┆ time_unit ┆ model_grou ┆ scenario_ ┆ ffibs_typ ┆ calendar_ ┆ path      │
│ ---        ┆ ---        ┆ ---       ┆ p_id       ┆ id        ┆ e         ┆ year      ┆ ---       │
│ str        ┆ str        ┆ str       ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│            ┆            ┆           ┆ i32        ┆ i32       ┆ str       ┆ i32       ┆           │
╞════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_bf     ┆ 2019      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_bf     ┆ 2020      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_bf     ┆ 2021      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_bf     ┆ 2022      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_bf     ┆ 2023      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ …          ┆ …          ┆ …         ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_sm     ┆ 2066      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_sm     ┆ 2067      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_sm     ┆ 2068      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_sm     ┆ 2069      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
│ ffibs_cove ┆ veg_grid_c ┆ annual    ┆ 500        ┆ 7         ┆ pl_sm     ┆ 2070      ┆ /ocean/pr │
│ rage_ratio ┆ ell_v001   ┆           ┆            ┆           ┆           ┆           ┆ ojects/bc │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ s200002p/ │
│            ┆            ┆           ┆            ┆           ┆           ┆           ┆ sha…      │
└────────────┴────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [3]:
%connect_info

{
  "shell_port": 57171,
  "iopub_port": 56629,
  "stdin_port": 48187,
  "control_port": 51109,
  "hb_port": 36341,
  "ip": "127.0.0.1",
  "key": "6aaa8b5c-1757f4d4c805b39f6fd150bb",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "cpra",
  "jupyter_session": "/jet/home/hjaehn/jupyter/read_data_example.ipynb"
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-f738f3cf-3c97-4164-afa7-0886e768eb22.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.

In [4]:
import sys
print("Current Python executable:", sys.executable)
print("Python version:", sys.version)

Current Python executable: /opt/conda/bin/python3
Python version: 3.12.11 | packaged by conda-forge | (main, Jun  4 2025, 14:45:31) [GCC 13.3.0]

In [1]:
!pip list

Package                   Version
------------------------- --------------
affine                    2.4.0
alembic                   1.16.4
altair                    5.5.0
annotated-types           0.7.0
anyio                     4.10.0
archspec                  0.2.5
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.3.0
asttokens                 3.0.0
async_generator           1.10
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.4
bleach                    6.2.0
blinker                   1.9.0
bokeh                     3.7.3
boltons                   25.0.0
Bottleneck                1.5.0
Brotli                    1.1.0
cached-property           1.5.2
cachetools                6.2.1
certifi                   2025.8.3
certipy                   0.2.2
cffi                      1.17.1
charset-normalizer        3.4.3
click                     8.2.1
click-plugins             1.1.1.2
cligj                     0.7.2
cloudpickle               3.1.1
colorama                  0.4.6
comm                      0.2.3
conda                     25.7.0
conda-libmamba-solver     25.4.0
conda-package-handling    2.4.0
conda_package_streaming   0.12.0
contourpy                 1.3.3
cpra-mp-data              0.32.1
cryptography              45.0.6
cycler                    0.12.1
Cython                    3.1.2
cytoolz                   1.0.1
dask                      2025.7.0
debugpy                   1.8.16
decorator                 5.2.1
defusedxml                0.7.1
dill                      0.4.0
distributed               2025.7.0
distro                    1.9.0
et_xmlfile                2.0.0
exceptiongroup            1.3.0
executing                 2.2.0
fastjsonschema            2.21.1
fonttools                 4.59.0
fqdn                      1.5.1
frozendict                2.4.6
fsspec                    2025.7.0
gitdb                     4.0.12
GitPython                 3.1.45
gmpy2                     2.2.1
greenlet                  3.2.4
h11                       0.16.0
h2                        4.2.0
h5py                      3.14.0
hpack                     4.1.0
httpcore                  1.0.9
httpx                     0.28.1
hyperframe                6.1.0
idna                      3.10
imagecodecs               2025.8.2
imageio                   2.37.0
importlib_metadata        8.7.0
ipykernel                 6.30.1
ipympl                    0.9.7
ipython                   9.4.0
ipython_genutils          0.2.0
ipython_pygments_lexers   1.1.1
ipywidgets                8.1.7
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
joblib                    1.5.1
json5                     0.12.0
jsonpatch                 1.33
jsonpointer               3.0.0
jsonschema                4.25.0
jsonschema-specifications 2025.4.1
jupyter_client            8.6.3
jupyter_core              5.8.1
jupyter-events            0.12.0
jupyter-lsp               2.2.6
jupyter_server            2.16.0
jupyter_server_mathjax    0.2.6
jupyter_server_terminals  0.5.3
jupyterhub                5.3.0
jupyterlab                4.4.5
jupyterlab_git            0.51.2
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.15
kiwisolver                1.4.9
lark                      1.2.2
lazy_loader               0.4
libmambapy                2.3.1
llvmlite                  0.44.0
locket                    1.0.0
lz4                       4.4.4
Mako                      1.3.10
MarkupSafe                3.0.2
matplotlib                3.10.5
matplotlib-inline         0.1.7
menuinst                  2.3.1
mercantile                1.2.1
mistune                   3.1.3
mpmath                    1.3.0
msgpack                   1.1.1
munkres                   1.1.4
narwhals                  2.1.0
nbclassic                 1.3.1
nbclient                  0.10.2
nbconvert                 7.16.6
nbdime                    4.0.2
nbformat                  5.10.4
nest_asyncio              1.6.0
networkx                  3.5
notebook                  7.4.5
notebook_shim             0.2.4
numba                     0.61.2
numexpr                   2.10.2
numpy                     2.2.6
oauthlib                  3.3.1
openpyxl                  3.1.5
overrides                 7.7.0
packaging                 25.0
pamela                    1.2.0
pandas                    2.3.1
pandocfilters             1.5.0
parso                     0.8.4
partd                     1.4.2
patsy                     1.0.1
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    11.3.0
pip                       25.2
platformdirs              4.3.8
pluggy                    1.6.0
polars                    1.35.2
polars-runtime-32         1.35.2
prometheus_client         0.22.1
prompt_toolkit            3.0.51
protobuf                  6.31.1
psutil                    7.0.0
psycopg2-binary           2.9.11
ptyprocess                0.7.0
pure_eval                 0.2.3
py-cpuinfo                9.0.0
pyarrow                   21.0.0
pycosat                   0.6.6
pycparser                 2.22
pycrypto                  2.6.1
pydantic                  2.11.7
pydantic_core             2.33.2
Pygments                  2.19.2
PyJWT                     2.10.1
pyparsing                 3.2.3
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.2.1
python-json-logger        2.0.7
pytz                      2025.2
PyWavelets                1.9.0
PyYAML                    6.0.2
pyzmq                     27.0.1
rasterio                  1.4.3
referencing               0.36.2
requests                  2.32.4
rfc3339_validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.27.0
ruamel.yaml               0.18.14
ruamel.yaml.clib          0.2.8
scikit-image              0.25.2
scikit-learn              1.7.1
scipy                     1.16.0
seaborn                   0.13.2
Send2Trash                1.8.3
setuptools                80.9.0
six                       1.17.0
smmap                     5.0.2
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.7
SQLAlchemy                2.0.42
stack_data                0.6.3
statsmodels               0.14.5
sympy                     1.14.0
tables                    3.10.2
tblib                     3.1.0
terminado                 0.18.1
threadpoolctl             3.6.0
tifffile                  2025.6.11
tinycss2                  1.4.0
tomli                     2.2.1
toolz                     1.0.0
tornado                   6.5.2
tqdm                      4.67.1
traitlets                 5.14.3
truststore                0.10.3
types-python-dateutil     2.9.0.20250809
typing_extensions         4.14.1
typing-inspection         0.4.1
typing_utils              0.1.0
tzdata                    2025.2
unicodedata2              16.0.0
uri-template              1.3.0
urllib3                   2.5.0
wcwidth                   0.2.13
webcolors                 24.11.1
webencodings              0.5.1
websocket-client          1.8.0
wheel                     0.45.1
widgetsnbextension        4.0.14
xlrd                      2.0.1
xyzservices               2025.4.0
zict                      3.0.0
zipp                      3.23.0
zstandard                 0.23.0